# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import json
import random
from dataclasses import dataclass
from pathlib import Path

GRAPH_DEPTH = 6
MAX_UPSTREAMS = 4
GENERATED_HEADER = "-- Generated by examples/randomgraphs/generate_model_graph.py"
DEFAULT_OUTPUT_DIR = Path(__file__).parent / "models" / "generated"


@dataclass(frozen=True)
class GeneratedGraph:
    """Description of a generated SQLMesh model graph."""

    input_models: tuple[str, ...]
    input_row_counts: dict[str, int]
    layers: tuple[tuple[str, ...], ...]
    dependencies: dict[str, tuple[str, ...]]
    model_paths: tuple[Path, ...]
    manifest_path: Path


def generate_model_graph(
    n: int,
    *,
    output_dir: Path | str = DEFAULT_OUTPUT_DIR,
    seed: int = 0,
    min_rows_per_input: int = 10,
    max_rows_per_input: int = 1000,
) -> GeneratedGraph:
    """Generate ``n`` input models and six layers of ``n`` materialized views.

    Each materialized view reads between one and four distinct models from the
    immediately preceding layer. For widths greater than one, every view has at
    least two inputs so its query contains a join. A fixed output schema and
    unique ``(entity_id, bucket_id)`` grain make every randomly generated join
    and aggregation valid.
    """
    if isinstance(n, bool) or not isinstance(n, int) or n <= 0:
        raise ValueError("n must be a positive integer")
    valid_row_bounds = (
        not isinstance(min_rows_per_input, bool)
        and isinstance(min_rows_per_input, int)
        and not isinstance(max_rows_per_input, bool)
        and isinstance(max_rows_per_input, int)
        and min_rows_per_input > 0
        and max_rows_per_input >= min_rows_per_input
    )
    if not valid_row_bounds:
        raise ValueError("row bounds must be positive integers with minimum <= maximum")

    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    _remove_stale_generated_models(destination)

    rng = random.Random(seed)
    row_rng = random.Random(seed ^ 0x5DEECE66D)
    model_paths: list[Path] = []
    dependencies: dict[str, tuple[str, ...]] = {}

    input_models = tuple(f"generated.input_{index:04d}" for index in range(n))
    input_row_counts = {
        model_name: row_rng.randint(min_rows_per_input, max_rows_per_input)
        for model_name in input_models
    }
    for index, model_name in enumerate(input_models):
        path = destination / f"input_{index:04d}.sql"
        path.write_text(
            _render_input_model(model_name, index, input_row_counts[model_name]),
            encoding="utf-8",
        )
        model_paths.append(path)
        dependencies[model_name] = ()

    layers: list[tuple[str, ...]] = []
    previous_layer = input_models
    for depth in range(1, GRAPH_DEPTH + 1):
        layer = tuple(f"generated.mv_d{depth:02d}_{index:04d}" for index in range(n))
        for index, model_name in enumerate(layer):
            maximum = min(MAX_UPSTREAMS, len(previous_layer))
            minimum = 2 if maximum >= 2 else 1
            upstream_count = rng.randint(minimum, maximum)
            upstreams = tuple(sorted(rng.sample(previous_layer, upstream_count)))
            dependencies[model_name] = upstreams

            path = destination / f"mv_d{depth:02d}_{index:04d}.sql"
            path.write_text(_render_materialized_view(model_name, upstreams), encoding="utf-8")
            model_paths.append(path)

        layers.append(layer)
        previous_layer = layer

    manifest_path = destination / "graph.json"
    manifest_path.write_text(
        json.dumps(
            {
                "depth": GRAPH_DEPTH,
                "width": n,
                "seed": seed,
                "min_rows_per_input": min_rows_per_input,
                "max_rows_per_input": max_rows_per_input,
                "input_models": input_models,
                "input_row_counts": input_row_counts,
                "layers": layers,
                "dependencies": dependencies,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return GeneratedGraph(
        input_models=input_models,
        input_row_counts=input_row_counts,
        layers=tuple(layers),
        dependencies=dependencies,
        model_paths=tuple(model_paths),
        manifest_path=manifest_path,
    )


def chunk_model_graph(
    graph: GeneratedGraph, *, chunk_count: int = 10
) -> tuple[tuple[str, ...], ...]:
    """Split a generated graph into balanced chunks in topological order.

    The ordering places every input first, followed by each materialized-view
    layer in depth order. Consequently, every upstream model occurs in the same
    or an earlier chunk than its downstream model. Chunk sizes differ by at
    most one, with any remainder assigned to the earliest chunks.
    """
    ordered_models = (
        *graph.input_models,
        *(model_name for layer in graph.layers for model_name in layer),
    )
    if (
        isinstance(chunk_count, bool)
        or not isinstance(chunk_count, int)
        or chunk_count <= 0
        or chunk_count > len(ordered_models)
    ):
        raise ValueError("chunk_count must be a positive integer no greater than model count")

    minimum_size, remainder = divmod(len(ordered_models), chunk_count)
    chunks: list[tuple[str, ...]] = []
    start = 0
    for chunk_index in range(chunk_count):
        chunk_size = minimum_size + (chunk_index < remainder)
        end = start + chunk_size
        chunks.append(tuple(ordered_models[start:end]))
        start = end

    return tuple(chunks)


def _remove_stale_generated_models(output_dir: Path) -> None:
    for path in output_dir.glob("*.sql"):
        with path.open(encoding="utf-8") as file:
            if file.readline().rstrip() == GENERATED_HEADER:
                path.unlink()


def _render_input_model(model_name: str, index: int, rows_per_input: int) -> str:
    multiplier = index + 1
    return f"""{GENERATED_HEADER}
MODEL (
  name {model_name},
  kind FULL,
  grain (entity_id, bucket_id),
  columns (
    entity_id BIGINT,
    bucket_id INTEGER,
    total_value DECIMAL(38, 6),
    row_count BIGINT
  )
);

SELECT
  series_id::BIGINT AS entity_id,
  (series_id % 16)::INTEGER AS bucket_id,
  (series_id * {multiplier})::DECIMAL(38, 6) AS total_value,
  1::BIGINT AS row_count
FROM GENERATE_SERIES(1, {rows_per_input}) AS source(series_id);
"""


def _render_materialized_view(model_name: str, upstreams: tuple[str, ...]) -> str:
    aliases = [f"u{index}" for index in range(len(upstreams))]
    value_sum = " + ".join(f"{alias}.total_value" for alias in aliases)
    count_sum = " + ".join(f"{alias}.row_count" for alias in aliases)

    joins = "\n".join(
        f"JOIN {upstream} AS {alias}\n"
        f"  ON u0.entity_id = {alias}.entity_id\n"
        f"  AND u0.bucket_id = {alias}.bucket_id"
        for upstream, alias in zip(upstreams[1:], aliases[1:])
    )
    if joins:
        joins = f"\n{joins}"

    return f"""{GENERATED_HEADER}
MODEL (
  name {model_name},
  kind CUSTOM (
    materialization 'postgres_materialized_view'
  ),
  grain (entity_id, bucket_id),
  columns (
    entity_id BIGINT,
    bucket_id INTEGER,
    total_value DECIMAL(38, 6),
    row_count BIGINT
  )
);

SELECT
  u0.entity_id::BIGINT AS entity_id,
  u0.bucket_id::INTEGER AS bucket_id,
  SUM({value_sum})::DECIMAL(38, 6) AS total_value,
  SUM({count_sum})::BIGINT AS row_count
FROM {upstreams[0]} AS u0{joins}
GROUP BY
  u0.entity_id,
  u0.bucket_id;
"""


def _main() -> None:
    parser = argparse.ArgumentParser(description=generate_model_graph.__doc__)
    parser.add_argument("n", type=int, help="Number of models in each graph layer")
    parser.add_argument("--seed", type=int, default=0, help="Random graph seed")
    parser.add_argument(
        "--min-rows-per-input",
        type=int,
        default=10,
        help="Minimum rows generated by each input model",
    )
    parser.add_argument(
        "--max-rows-per-input",
        type=int,
        default=1000,
        help="Maximum rows generated by each input model",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for generated SQL models",
    )
    args = parser.parse_args()

    graph = generate_model_graph(
        args.n,
        output_dir=args.output_dir,
        seed=args.seed,
        min_rows_per_input=args.min_rows_per_input,
        max_rows_per_input=args.max_rows_per_input,
    )
    print(
        f"Generated {len(graph.model_paths)} models "
        f"({len(graph.input_models)} inputs and {GRAPH_DEPTH} layers) in "
        f"{Path(args.output_dir).resolve()}"
    )


if __name__ == "__main__":
    _main()
